import About from '@/components/About'
import Contact from '@/components/Contact'
import Feature from '@/components/Features'
import FeaturesTab from '@/components/FeaturesTab'
import Hero from '@/components/Hero'
import Integration from '@/components/Integration'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Portfolio App',
  description: 'Generated by nextjs,typescript and tailwind css',
}
export default function Home() {
  return (
    <main>
      <Hero />
      <Feature />
      <About />
      <FeaturesTab />
      <Integration />
      <Contact />
    </main>
  )
}
